export const TAGS = {
	AUTO_SAVER: Symbol('auto_saver'),
	BRANCHES_MAPS_REF: Symbol('branches_map_ref'),
	CONTENT_ID_SIGMA_IDS_MAP: Symbol('contentIdSigmaIdsMap'),
	CONTENT_ID_MAP_ID_MAP_SOURCE: Symbol('contentIdMapIdMapSource'),
	CONTENT_ID_MAP_ID_MAP_REF: Symbol('contentIdMapIdMapRef'),
	CONTENT_DATA: Symbol('CONTENT_DATA'),
	CONTENT_USERS_DATA: Symbol('CONTENT_USERS_DATA'),
	CONTENT_REF: Symbol('content_ref'),
	CONTENT_USERS_REF: Symbol('content_users_ref'),
	DEFAULT: Symbol('default'),
	DEFAULT_UIS_ARRAY: Symbol('default_uis_array'),
	DRAG_LISTENER: Symbol('drag_listener'),
	MAIN_APP: Symbol('main_app'),
	MAIN_SIGMA_INSTANCE: Symbol('main_sigma_instance'),
	OVERDUE_LISTENER: Symbol('overdue_listener'),
	SPECIAL_TREE_LOADER: Symbol('special_tree_loader'),
	TESTING: Symbol('testing'),
	TREES_REF: Symbol('trees_ref'),
	TREE_DATA: Symbol('tree_data'),
	TREE_LOCATIONS_DATA: Symbol('TREE_LOCATIONS_DATA'),
	TREE_USERS_DATA: Symbol('TREE_USERS_DATA'),
	TREE_LOCATIONS_REF: Symbol('tree_locations_ref'),
	TREE_USERS_REF: Symbol('tree_users_ref'),
	USERS_REF: Symbol('users_ref'),
};
