const TYPES = {
    Any: Symbol('Any'),
    Array: Symbol('Array'),
    Boolean: Symbol('Boolean'),
    ContentUserDataArgs: Symbol('ContentUserDataArgs'),
    FirebaseSaverArgs: Symbol('FirebaseSaverArgs'),
    FirebaseSyncerArgs: Symbol('SyncToDBArgs'),
    IActivatableDatedMutation: Symbol('IActivatableDatedMutation'),
    IActivatableDatedMutationArr: Symbol('IActivatableDatedMutationArr'),
    IBasicTree: Symbol('IBasicTree'),
    IContentUserData: Symbol('IContentUserData'),
    IDatabaseSyncer: Symbol('IDatabaseSyncer'),
    IFirebaseRef: Symbol('IFirebaseRef'),
    IMutableId: Symbol('IMutableId'),
    IMutableStringSet: Symbol('IMutableStringSet'),
    ISigmaNode: Symbol('ISigmaNode'),
    ISubscribableBasicTree: Symbol('ISubscribableBasicTree'),
    ISubscribableMutableId: Symbol('ISubscribableMutableId'),
    ISubscribableMutableIdArgs: Symbol('ISubscribableMutableIdArgs'),
    ISubscribableMutableStringSet: Symbol('ISubscribableMutableStringSet'),
    Number: Symbol('Number'),
    Object: Symbol('Object'),
    PROFICIENCIES: Symbol('PROFICIENCIES'),
    SaveUpdatesToDBFunction: Symbol('SaveUpdatesToDBFunction'),
    SigmaNodeArgs: Symbol('SigmaNodeArgs'),
    String: Symbol('String'),
    Subscribable: Symbol('Subscribable'),
    SubscribableArgs: Symbol('SubscribableArgs'),
    SubscribableBasicTreeArgs: Symbol('SubscribableBasicTreeArgs'),
    SubscribableMutableStringSetArgs: Symbol('SubscribableMutableStringSetArgs'),
    SyncToDBArgs: Symbol('SyncToDBArgs'),
    SyncToFirebaseArgs: Symbol('SyncToDBArgs')
}

export {TYPES}
