# https://docs.travis-ci.com/user/encrypting-files/
language: node_js
node_js:
- '6.9.2'
script: npm test
before_install:
#- openssl aes-256-cbc -K $encrypted_090e6e0a8545_key -iv $encrypted_090e6e0a8545_iv
  #-in branches.pem.enc -out branches.pem -d
#- export DISPLAY=:99.0
#- sh -e /etc/init.d/xvfb start
before_script:
- npm install
