import {log} from '../app/core/log'
log('myContainer', window, document, HTMLElement)
import "./sigma/sigma.core.js"
import "./sigma/conrad.js"
import "./sigma/utils/sigma.utils.js"
import "./sigma/utils/sigma.utils.branches.js"
// import "./sigma/utils/sigma.polyfills.js" // << didn't refactor
import "./sigma/sigma.settings.js"
import "./sigma/classes/sigma.classes.dispatcher.js"
import "./sigma/classes/sigma.classes.configurable.js"
import "./sigma/classes/sigma.classes.graph.js"
import "./sigma/classes/sigma.classes.camera.js"
import "./sigma/classes/sigma.classes.quad.js"
import "./sigma/classes/sigma.classes.edgequad.js"
import "./sigma/captors/sigma.captors.mouse.js"
import "./sigma/captors/sigma.captors.touch.js"
import "./sigma/renderers/sigma.renderers.canvas.js"
import "./sigma/renderers/sigma.renderers.webgl.js"
import "./sigma/renderers/sigma.renderers.svg.js"
import "./sigma/renderers/sigma.renderers.def.js"
import "./sigma/renderers/canvas/sigma.canvas.labels.def.js"
import "./sigma/renderers/canvas/sigma.canvas.hovers.def.js"
import "./sigma/renderers/canvas/sigma.canvas.nodes.def.js"
import "./sigma/renderers/canvas/sigma.canvas.edges.def.js"
import "./sigma/renderers/canvas/sigma.canvas.edgehovers.def.js"
import "./sigma/renderers/canvas/sigma.canvas.extremities.def.js"
import "./sigma/middlewares/sigma.middlewares.rescale.js"
import "./sigma/middlewares/sigma.middlewares.copy.js"
import "./sigma/misc/sigma.misc.animation.js"
import "./sigma/misc/sigma.misc.bindEvents.js"
import "./sigma/misc/sigma.misc.bindDOMEvents.js"
import "./sigma/misc/sigma.misc.drawHovers.js"
import "./sigma/plugins/dragNode.js"
import "./sigma/plugins/sigma.plugins.tooltips/sigma.plugins.tooltips.js"
