export enum SIGMA_EVENT_NAMES {
	CLICK_NODE = 'SIGMA_EVENT_NAMES_CLICK_NODE',
	DOUBLE_CLICK_NODE = 'SIGMA_EVENT_NAMES_DOUBLE_CLICK_NODE',
	OVER_NODE = 'SIGMA_EVENT_NAMES_OVER_NODE',
	CLICK_STAGE = 'SIGMA_EVENT_NAMES_CLICK_STAGE',
	DRAG_END = 'SIGMA_EVENT_NAMES_DRAG_END'
}
